spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
app:
  image:
    bucket: "C:\\Java\\Projects\\dmdev2\\images"