spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  mvc:
    format:
      date: iso
  messages:
    basename: messages
app:
  image:
    bucket: "C:\\Java\\Projects\\dmdev2\\images"
    bucket-for-goods: "\\goods\\"
    bucket-for-users: "\\users\\"
